<?php
return array(
		'apiSuccess' => 'Success', // success string return when the api was called successfully
		
		'SITE_NAME' => 'BLUEBEE',
		'SITE_NAME_CAP' => 'BLUEBEE',
		
		'SESSION_DURATION' => 3600*24*7,
		
		'NUMBER_ENTITY_PER_PAGE_DEFAULT' => 10,	//size for each page in list view
		
		'TRANSLATE_FILE' => 'TRANSLATE_FILE',
		
		'PAGINATION_MODEL' => 'model',
		'PAGINATION_PAGE' => 'pages',
		'PAGINATION_CURRENT_PAGE' => 'currentPages',
		'PAGINATION_PAGE_SIZE' => 'pagesize',
		'PAGINATION_ITEM_COUNT' => 'item_count',
		
		'NAV_API_MANAGER_INDEX' => 0,
		
		'SEARCH_FORM_AJAX_ELEMENT_TYPE' => 0,
		'SEARCH_FORM_AJAX_ELEMENT_VALUE' => 1,
		'SEARCH_FORM_AJAX_ELEMENT_MODEL_NAME' => 2,
		
		'SEARCH_INPUT_TYPE_TEXT' => 0,
		'SEARCH_INPUT_TYPE_BOOL' => 1,
		'SEARCH_INPUT_TYPE_DATE_UPPER' => 2,
		'SEARCH_INPUT_TYPE_DATE_LOWER' => 3,
                'SEARCH_INPUT_TYPE_NUMBER' => 4,
		
		'PERMISSION_GLOBAL_CREATE_UPDATE_PROJECT' => 0,
		'PERMISSION_GLOBAL_DELETE_PROJECT' => 1,
		'PERMISSION_GLOBAL_VIEW_CLOSED_PROJECT' => 2,
		'PERMISSION_GLOBAL_VIEW_PROJECT_HISTORY' => 3,
		'PERMISSION_GLOBAL_CREATE_UPDATE_USER' => 4,
		'PERMISSION_GLOBAL_DELETE_USER' => 5,
		'PERMISSION_GLOBAL_CREATE_EDIT_CLIENT' => 6,
		'PERMISSION_GLOBAL_DELETE_CLIENT' => 8,
		'PERMISSION_PROJECT_VIEW' => 9,
		'PERMISSION_PROJECT_UPDATE' => 10,
		'PERMISSION_PROJECT_UPLOAD' => 11,
		'PERMISSION_PROJECT_VIEW_WHEN_CLOSED' => 12,
		'PERMISSION_PROJECT_VIEW_HISTORY' => 13,
		'PERMISSION_ADMINISTRATOR' => 14,
		
		'DATE_FORMAT' => 'Y/m/d H:i:s',
		'DATE_FORMAT_DATE_ONLY' => 'Y/m/d',
);
?>